"""Pitch-facing tab: what we built (tied to judging criteria) and where
we're taking it (Now / Next / Later roadmap), each with a working demo —
Now/Next use real data already in the app; Later is explicitly labeled
illustrative (no real system exists to connect to yet).
"""

import pandas as pd
import streamlit as st

from theme import ACCENT, BORDER, TEXT_PRIMARY, TEXT_SECONDARY

FEATURES = [
    {
        "title": "Real-time data agent",
        "desc": "Local LLM + LangGraph routes questions to 6 tools over the real 2026 FVL data — every number is computed, never generated by the model.",
        "proves": "Data analysis · AI integration",
    },
    {
        "title": "Matching engine, tested on real data",
        "desc": "33.5% of empty-running trips had a real, pre-existing nearby departure — a measured result on the actual 2026 data, not a proposal.",
        "proves": "Solution quality · Feasibility",
    },
    {
        "title": "Dispatcher simulation, real trucks",
        "desc": "Real license plates, real historical Loading Factor, capped to a realistic range — not a fictional fleet.",
        "proves": "Solution originality",
    },
    {
        "title": "Adjustable alert threshold",
        "desc": "Move the slider, watch the real-data validation (28% / 94%, disclosed both ways) recalculate live — transparency built in, not bolted on.",
        "proves": "Analytical rigor",
    },
    {
        "title": "Real trip routes",
        "desc": "Trip options are the actual most-frequent Departure to Delivery pairs per compound, with real distances.",
        "proves": "Grounded realism",
    },
    {
        "title": "Production-ready UI",
        "desc": "CEVA-branded, dense dashboard layout, built to be used on a laptop during a live shift — not a Dribbble concept.",
        "proves": "Feasibility · Execution",
    },
]

ROADMAP = [
    {"horizon": "NOW", "title": "Pilot at Le Havre", "period": "8-12 weeks",
     "desc": "Deploy the matching engine as the dispatcher's live tool. Success = cut empty-km share from 41.5% toward 30%."},
    {"horizon": "NEXT", "title": "Scale + go fully real", "period": "",
     "desc": "Roll out to the rest of the top-10 origins (81% of the problem). Replace the last mock piece — car inventory — with CEVA's real vehicle tracking. Connect the chat agent to the dispatcher."},
    {"horizon": "LATER", "title": "Platform vision", "period": "",
     "desc": "TMS-integrated live dispatch across the whole network. Same logic extended to the EV/multi-energy fleet transition. Spare-capacity visibility as a business lever, not just cost avoidance."},
]


def _feature_card(f: dict) -> None:
    st.markdown(
        f'<div style="border:1px solid {BORDER};border-radius:8px;padding:16px 18px;height:172px;">'
        f'<div style="font-size:14px;font-weight:600;color:{TEXT_PRIMARY};margin-bottom:6px;">{f["title"]}</div>'
        f'<div style="font-size:12.5px;color:{TEXT_SECONDARY};line-height:1.5;">{f["desc"]}</div>'
        f'<div style="font-size:11px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;'
        f'color:{ACCENT};margin-top:10px;">{f["proves"]}</div>'
        "</div>",
        unsafe_allow_html=True,
    )


def _roadmap_card(r: dict) -> None:
    period = f' <span style="color:{TEXT_SECONDARY};font-weight:400;">— {r["period"]}</span>' if r["period"] else ""
    st.markdown(
        f'<div style="border:1px solid {BORDER};border-radius:8px;padding:18px 20px;">'
        f'<div style="font-size:11px;font-weight:700;letter-spacing:.08em;color:{ACCENT};">{r["horizon"]}</div>'
        f'<div style="font-size:15px;font-weight:600;color:{TEXT_PRIMARY};margin-top:6px;">{r["title"]}{period}</div>'
        f'<div style="font-size:12.5px;color:{TEXT_SECONDARY};line-height:1.5;margin-top:8px;">{r["desc"]}</div>'
        "</div>",
        unsafe_allow_html=True,
    )


def _roadmap_demo(horizon: str, shares: dict) -> None:
    if horizon == "NOW":
        with st.expander("Try it — live pilot number"):
            st.metric("Le Havre empty-km share (real, live)", f"{shares['CEVA LE HAVRE']:.1%}")
            st.caption("Same number the Dispatcher check tab is built around — open that tab to run the full pilot simulation.")
    elif horizon == "NEXT":
        with st.expander("Try it — scaling preview (real data)"):
            for name, share in shares.items():
                st.write(f"**{name.replace('CEVA ', '')}**: {share:.1%} empty-km share")
            st.caption("All 3 are already selectable in the Dispatcher check tab today — scaling is a rollout decision, not a new build.")
            truck = st.session_state.get("picked_truck")
            if truck:
                st.divider()
                st.write(
                    f"Connected preview: you picked **{truck['plate']}** in the dispatcher — the same "
                    f"'Ask the data' agent already knows its real historical max ({truck['maxLoading']}), no separate integration needed."
                )
            else:
                st.caption("Pick a truck in the Dispatcher check tab, then come back here to see this live.")
    else:
        with st.expander("Try it — illustrative preview (sample data, not a real system)"):
            st.caption("SAMPLE — illustrative only, not connected to any real system or dataset.")
            mix = st.slider("ICE share of fleet mix (illustrative 2030 scenario)", 0, 100, 60, key="ev_mix_demo")
            st.write(f"At {mix}% ICE / {100 - mix}% EV, illustrative average loading capacity per truck would need re-calibrating (EVs load differently) — sample only, not measured.")
            st.dataframe(
                pd.DataFrame({"Carrier (sample)": ["Carrier A", "Carrier B", "Carrier C"],
                              "Spare capacity offered (sample)": [1.2, 0.8, 2.1]}),
                hide_index=True,
            )


def render_features(shares: dict) -> None:
    st.subheader("What we built")
    for row_start in (0, 3):
        cols = st.columns(3, gap="medium")
        for col, f in zip(cols, FEATURES[row_start:row_start + 3]):
            with col:
                _feature_card(f)

    st.divider()
    st.subheader("Where we're taking it")
    cols = st.columns(3, gap="medium")
    for col, r in zip(cols, ROADMAP):
        with col:
            _roadmap_card(r)
            _roadmap_demo(r["horizon"], shares)
